sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
env:
  NODE_ENV: test
script:
  - docker-compose -f docker-compose.prod.yml build
  - docker-compose -f docker-compose.prod.yml up
  - docker-compose -f docker-compose.prod.yml run planet-clock npm test:ci
