sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
env:
  NODE_ENV: production 
script:
  - docker-compose -f docker-compose.prod.yml build
  - docker-compose -f docker-compose.prod.yml up
  - docker-compose -f docker-compose.prod.yml down --rmi all -v
  - npm test
