sudo: required
services:
  - docker
env:
  NODE_ENV: production
script:
  - docker-compose build
  - docker-compose up --no-start
  - docker-compose run planet-clock npm run build
  - docker-compose run planet-clock npm run test:ci
deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_TOKEN}
  app: planet-clock
  on: master
  skip_cleanup: true
after_deploy:
  - docker-compose down --rmi all -v
