sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
env:
  NODE_ENV: production
script:
  - docker-compose build
  - docker-compose run planet-clock npm run build
  - docker-compose run planet-clock npm test
deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_TOKEN}
  app: planet-clock
  on: 
    all_branches: true
  skip_cleanup: true
after_deploy:
  - docker-compose --rmi all -v