sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
env:
  NODE_ENV: test
install:
  - docker pull busybox
  - docker save busybox | gzip > docker/busybox.tar.gz
cache:
  directories:
    - docker
before_script:
  - gzip -dc docker/busybox.tar.gz | docker load
script:
  - docker-compose -f docker-compose.prod.yml build
  - docker-compose -f docker-compose.prod.yml up
  - docker-compose -f docker-compose.prod.yml run planet-clock npm run test:ci
