sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
env:
  NODE_ENV: production
script:
  - docker-compose build
  - docker-compose up
  - docker-compose run planet-clock npm run build
  - docker-compose run planet-clock npm test
before_deploy:
  - npm install -g serve
deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_TOKEN}
  app: planet-clock
  on: 
    all_branches: true
  skip_cleanup: true
  run: 
    - serve -s ./build
after_deploy:
  - docker-compose -f docker-compose.prod.yml down --rmi all -v