version: '3.3'

services:
  planet-clock:
    container_name: planet-clock
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=production
    command: npm run build
